#!/usr/bin/env python3
"""Create an isolated MC database with explicit GEM input formats."""
import argparse
from pathlib import Path
import shutil
import re

def configure(path, prefix, mode):
    # Normalize every tracker-level definition across date sections. Missing
    # keys are inserted before the first timestamp, as global defaults. Module
    # overrides retain the usual Podd precedence.
    text = path.read_text()
    values = {"mc_input_mode": mode}
    if mode:
        values.update(onlinezerosuppress=int(mode == 1), correct_common_mode=0)
    if mode == 3:
        values["commonmode_flag"] = 0
    defaults = []
    for key, value in values.items():
        pattern = rf"^{re.escape(prefix)}\.{key}\s*=.*$"
        replacement = f"{prefix}.{key} = {value}"
        text, count = re.subn(pattern, replacement, text, flags=re.M)
        if not count:
            defaults.append(replacement)
    if defaults:
        text = "# GEM MC input profile generated by make_gem_mc_db.py\n" + "\n".join(defaults) + "\n\n" + text
    path.write_text(text)

def read_plane_calibration(path):
    """Read LIBSBSDIG's GEM_plane# format without reordering strips/APVs."""
    result, plane = {}, None
    for number, line in enumerate(path.read_text().splitlines(), 1):
        fields = line.split('#', 1)[0].split()
        if line.startswith("GEM_plane#"):
            plane = int(line.split()[1])
            if plane in result:
                raise ValueError(f"{path}:{number}: duplicate plane {plane}")
            result[plane] = {}
        elif fields:
            if plane is None or len(fields) != 3:
                raise ValueError(f"{path}:{number}: invalid calibration row")
            index, mean, rms = int(fields[0]), float(fields[1]), float(fields[2])
            import math
            if index in result[plane] or not math.isfinite(mean) or not math.isfinite(rms) or rms < 0:
                raise ValueError(f"{path}:{number}: duplicate index or invalid calibration")
            result[plane][index] = mean, rms
    return result

def convert_ft_calibration(database, ped_source=None, cm_source=None):
    """Translate physical MC plane indices into the replay hardware APV map."""
    path = database / "db_sbs.gemFT.dat"
    text = path.read_text()
    cards, module = {}, None
    for line in text.splitlines():
        bare = line.split('#', 1)[0].strip()
        match = re.match(r"sbs\.gemFT\.m(\d+)\.chanmap\s*=", bare)
        if match:
            module = int(match[1])
            continue
        if bare.startswith("sbs."):
            module = None
        fields = bare.split()
        if module is not None and len(fields) == 9 and fields[0].isdigit():
            crate, slot, mpd, gem, adc, i2c, pos, invert, axis = map(int, fields)
            key = (2 * module + axis, pos)
            hardware = (crate, slot, mpd, adc)
            if key in cards and cards[key] != hardware:
                raise ValueError(f"conflicting channel maps for {key}")
            cards[key] = hardware
    if not cards:
        raise ValueError("no FT APV mapping found")
    target = database / "gemped"
    target.mkdir(exist_ok=True)
    for source, key, filename, per_strip in [
        (ped_source, "pedfile", "ft_mc_pedestal_rms.dat", True),
        (cm_source, "cmfile", "ft_mc_commonmode.dat", False),
    ]:
        if source is None:
            continue
        calibration = read_plane_calibration(source)
        expected = {(plane, pos * 128 + ch if per_strip else pos)
                    for plane, pos in cards for ch in (range(128) if per_strip else [0])}
        supplied = {(plane, index) for plane, values in calibration.items() for index in values}
        if expected != supplied:
            raise ValueError(f"{source}: calibration/map mismatch: "
                             f"{len(expected-supplied)} missing, {len(supplied-expected)} extra entries")
        rows = [] if not per_strip else [f"# RMS from {source}; pedestal offsets absent in new MC"]
        for (plane, pos), hardware in sorted(cards.items()):
            hw = ' '.join(map(str, hardware))
            if per_strip:
                rows.append(f"APV {hw}")
                rows.extend(f"{ch} 0 {calibration[plane][128*pos+ch][1]:.12g}" for ch in range(128))
            else:
                mean, rms = calibration[plane][pos]
                rows.append(f"{hw} {mean:.12g} {rms:.12g}")
        (target / filename).write_text('\n'.join(rows) + '\n')
        replacement = f"sbs.gemFT.{key} = gemped/{filename}"
        text, count = re.subn(rf"^sbs\.gemFT\.{key}\s*=.*$", replacement, text, flags=re.M)
        if not count:
            text = replacement + '\n' + text
    path.write_text(text)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="new database directory; must not exist")
    parser.add_argument("--source", type=Path,
                        default=Path(__file__).resolve().parents[1] / "DB_MC")
    parser.add_argument("--ft-mode", required=True, type=int, choices=range(4))
    parser.add_argument("--fpp-mode", type=int, choices=range(4),
                        help="omit to preserve FPP's existing format (currently legacy)")
    parser.add_argument("--ft-ped-source", type=Path,
                        help="LIBSBSDIG FT pedestal file: use its RMS; offsets are zero for modes 1-3")
    parser.add_argument("--ft-cm-source", type=Path,
                        help="LIBSBSDIG FT per-APV CM mean/sigma file")
    args = parser.parse_args()
    if args.ft_mode == 0 and (args.ft_ped_source or args.ft_cm_source):
        parser.error("digitizer calibration import is for modes 1-3; preserve historical mode-0 calibration")
    source, output = args.source.resolve(), args.output.resolve()
    if output == source or source in output.parents or output in source.parents:
        parser.error("source and output must be separate, non-nested directories")
    if output.exists():
        parser.error("output already exists; choose a new directory")
    detectors = [("gemFT", args.ft_mode)]
    if args.fpp_mode is not None:
        detectors.append(("gemFPP", args.fpp_mode))
    # Validate before copying, including custom database files.
    for detector, _ in detectors:
        path = source / f"db_sbs.{detector}.dat"
        if not path.is_file():
            parser.error(f"missing database {path}")
    shutil.copytree(source, output)
    for detector, mode in detectors:
        configure(output / f"db_sbs.{detector}.dat", f"sbs.{detector}", mode)
    if args.ft_ped_source or args.ft_cm_source:
        convert_ft_calibration(output, args.ft_ped_source, args.ft_cm_source)
    print(f"DB_DIR={output}")

if __name__ == "__main__":
    main()
